url: "http://smartcorelib.org"
tagline: "Rust Machine Learning"
email: volodymyr.orlov@gmail.com
author: Volodymyr Orlov
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
years_updated: 2020-2021
smartcore_version: 0.1.0

exclude:
  - scripts
  - smartcorelib.code-workspace

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
